SMS.Web/Areas/Admin/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Autofac;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using SMS.Web.Areas.Admin.Models;

namespace SMS.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StudentsController : Controller
    {      
        
        private readonly IConfiguration _configaration;
        public StudentsController(IConfiguration configuration)
        {
            _configaration = configuration;
        }
        public IActionResult Index()
        {
            var model = Startup.AutofacContainer.Resolve<StudentModel>();
            return View(model);
        }
        public IActionResult AddStudent()
        {
            var model = new CreateStudentModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddStudent([
            Bind(nameof(CreateStudentModel.Name),
            nameof(CreateStudentModel.Email),
            nameof(CreateStudentModel.Department))] CreateStudentModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    model.Create();                    
                    return RedirectToAction("Index");
                }
                
                catch (Exception ex)
                {
                    //model.Response = new ResponseModel("Book creation failed.", ResponseType.Failure);
                }
            }
            return View(model);
        }

        public IActionResult GetStudents()
        {
            var tableModel = new DataTableAjaxRequestModels(Request);
            using var model = Startup.AutofacContainer.Resolve<StudentModel>();
            var data = model.GetStudents(tableModel);
            return Json(data);
        }
    }
}

SMS.Web/Areas/Admin/Views/Students/AddStudent.cshtml
@model SMS.Web.Areas.Admin.Models.CreateStudentModel
@{
    ViewData["Title"] = "AddBook";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>New Book</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">New Book</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Add a new book</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    @*<partial name="_ActionMessage" model="@Model.Response" />*@
                    <form asp-area="Admin" asp-controller="Students" asp-action="AddStudent" method="post" class="form-horizontal">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Email" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Department" class="col-md-2 control-label"></label>
                            <div class="col-md-10">
                                <input asp-for="Department" class="form-control" />
                                <span asp-validation-for="Department" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <input type="submit" class="btn btn-default" value="Submit" />
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->


@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

SMS.Web/Areas/Admin/Views/Students/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@section Styles
{
    <link rel="stylesheet" href="~/backend/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>DataTables</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">DataTables</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @*<partial name="_ActionMessage" model="@Model.Response" />*@
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Edition</th>
                                <th>Publish Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tfoot>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Edition</th>
                                <th>Publish Date</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div class="modal-body">
                    <p>Are you sure, you want to delete?</p>
                    <form id="deleteForm" action="/admin/books/deletebook" method="post">
                        @Html.AntiForgeryToken()
                        <input type="hidden" id="deleteId" value="" name="id" />
                    </form>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" id="deleteButton" class="btn btn-danger">Yes, Delete!</button>

                </div>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
</section>
<!-- /.content -->
@section Scripts
{
    <!-- DataTables -->
    <script src="~/backend/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/backend/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>

    <!-- page script -->
    <script>
        $(function () {
            $('#example1').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": "/Admin/Students/GetStudents",
                "columnDefs": [
                    {
                        "orderable": false,
                        "targets": 4,
                        "render": function (data, type, row) {
                            return `<button type="submit" class="btn btn-info btn-sm" onclick="window.location.href='/admin/books/editbook/${data}'" value='${data}'>
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Edit
                                        </button>
                                        <button type="submit" class="btn btn-danger btn-sm show-bs-modal" href="#" data-id='${data}' value='${data}'>
                                            <i class="fas fa-trash">
                                            </i>
                                            Delete
                                        </button>`;
                        }
                    }
                ]
            });

            $('#example1').on('click', '.show-bs-modal', function (event) {
                var id = $(this).data("id");
                var modal = $("#modal-default");
                modal.find('.modal-body p').text('Are you sure you want to delete this record?')
                //$("#deleteForm").attr("action", "/admin/category/delete/" + id );
                $("#deleteId").val(id);
                modal.modal('show');
            });

            $("#deleteButton").click(function () {
                $("#deleteForm").submit();
            });
        });
    </script>
}